### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by thewchan**
Because this and tracerite is now a dependency for Sanic, they needed to be added to Conda Forge in order for that distribution of the package to be updated to the most recent version. Not having an explicit license and an accompanying license file is a blocker to addese both this and tracerite on Conda Forge.

### CODE REVIEW

**Comment by Tronic** [comment]
I guess we can add the file, but please make it for PUBLIC DOMAIN and with no author information (not CC-0 or anything with a license text, just plain PD). We note that setup.py also lists MIT. We do this to help with organizations who might filter by license types, and PD obviously allows one to slap any license at all on the code.

MIT, CC-0 and other carry unnecessary license text that I do not want, as it obscures the simple meaning of PUBLIC DOMAIN. Some judiciaries might not technically recognize PUBLIC DOMAIN but we take that in practice it would be recognized as intended anyway, and adding a text like CC-0 does not help that at all.

**Comment by thewchan** [comment]
We can change the author filed to public domain, sure.

**Comment by Tronic** [comment]
Can you work with that edited version? No license text at all because PUBLIC DOMAIN is not a license...

**Comment by Tronic** [comment]
If that suits your organization needs, I'll merge it like that. Otherwise you might wish to check how you are supposed to handle plain PD, which certainly ought to be supported.

**Comment by thewchan** [comment]
Unsure, let me check with Conda Forge core team. There might be a PD license they prefer? I've seen people there use https://spdx.org/licenses/Unlicense.html. Would this work for you @Tronic ?

**Comment by Tronic** [comment]
I specifically want PUBLIC DOMAIN rather than one of the licenses that give away rights. This is because PD is a clear legal concept but each such text has its own nuances and differences, and they even are fairly long (e.g. CC0 I couldn't make myself read through). All licenses generally also expect an author, and I don't think just slapping "Public Domain" as author name is legally correct.

If the Conda organization for some reason cannot handle that, another approach is that you make a fork for packaging, where you use the original PD status, and add a MIT license with Conda packager as author, or whatever. But I would hope to see that the organization actually recognized PD as is, and didn't have to resort to such tricks. I mean, certainly the distribution already contains other packages that are PD, so this should be pretty much sorted out...

**Comment by thewchan** [comment]
Would the text of The [Unlicense](https://unlicense.org/) be too much? It does not require an author name:

> Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.

> In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain. We make this dedication for the benefit of the public at large and to the detriment of our heirs and successors. We intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

I understand your concern. I'll ask and see what they say.

**Comment by Tronic** [comment]
Okay, that text is reasonably short, explicitly assigns it to PD when possible, and doesn't keep any reservations (like requiring the text to be retained, like MIT does). Please update both PRs to use the Unlicense text.

**Comment by thewchan** [comment]
Great! Thanks for being accommodating to this!

**Review by Tronic — APPROVED** [review]

**Pull request merged**
